### ISSUE TITLE
Not working, handle is 0

### ISSUE THREAD

**Issue by S1mpanss1** [carlgwastaken/memify#2]
The handle seems to be 0. 
I tried to run in adminstrator mode, still wont work.

Ps. the file include path in main.cpp is still memory.h even though the name of the file is memify.h.

**Comment by carlgwastaken** [comment]
# Completely forgot about this project, a couple things.

1. The handle hijacking has been confirmed to not work. Using Process Hacker you can actually see that the handle is just straight up open to any game you try to open a handle too. Sorry about that, I will update the description of the project later. (Yes, i am working on a new one using DuplicateHandle, i've also been looking into injecting into other projects but i want a more plug and play solution).

2. I'm currently using memify for most of my projects not using a kernel level ac, and i'm able to open a handle. If i remember i'll compare them later and then update the project if i find something wrong.

Thanks for the patience. I also want to mention that the reason i'm not making a pr to update anything i the project description is that i don't want to give anyone false hope after 5 months of the project being unactive just to say "yea, just confirming this does infact not work". As soon as i get into game cheating projects agan i'll make sure to work on this project, but currently i have no idea when that is.
