### ISSUE TITLE
'processname' undeclared identifier

### ISSUE THREAD

**Issue by F8SDFSJ8** [carlgwastaken/memify#3]
So I'm very new to C++ and was just following along with your external aimbot tutorial but I got this error after trying to run the code and I've tried repasting the code several times and it just keeps giving me the same error. The error is in memify.h, I believe it can be fixed with an inline? Not too sure, as I said I'm extremely new to programming and want to learn game hacking.

**Comment by F8SDFSJ8** [comment]
For now I'll just use an older version since I'm not too worried about the cheat being undetected and just want to get an understanding of game hacking.

**Comment by F8SDFSJ8** [comment]
Nope cant be fixed with inline and now I sound stupid (I am), but this could be something on my end, I'm too sure but I've configured the project correctly.

**Comment by F8SDFSJ8** [comment]
I've fixed the issue. In the code

`uintptr_t GetProcessId(std::string_view processName)
{
	if (!handle) {
		// define processentry32
		PROCESSENTRY32 pe;
		pe.dwSize = sizeof(PROCESSENTRY32);

		// create a snapshot handle
		HANDLE ss = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);

		// loop through all process
		while (Process32Next(ss, &pe)) {
			// compare program names to processName
			if (!processName.compare(pe.szExeFile)) {
				processID = pe.th32ProcessID;
				return processID;
			}
		}
	}`
	
There was a simple typo `if (!processname.compare(pe.szExeFile)) {` should've been ``if (!processName.compare(pe.szExeFile)) {``

**Comment by carlgwastaken** [comment]
holy shit, my fault. i was writing the code in the github editor, and not in visual studio. Thanks for putting in all this effort!
